name: Create and publish docker image to GitHub Container Registry and Docker Hub

on:
  release:
    types: [published]

  push:
    tags:
      - 'v*'
    paths:
      - 'docker/makers-dockerfile'
      - 'bin/*'


jobs:
  build-and-push-image-to-registries:
    runs-on: ubuntu-24.04


    env:
      # DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/makers-docker

      GHCR_REGISTRY: ghcr.io
      # issue : organization "Infineon" with capital "I" not allowed.
      GHCR_IMAGE_NAME: infineon/makers-docker


    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write


    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          # username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_IMAGE_NAME }}
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}      
          tags: |
            type=semver,pattern={{version}}
 

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - if: ${{ github.event_name == 'push' }}
        name: Build and push docker image to GitHub Container Registry and Docker Hub
        id: push
        uses: docker/build-push-action@v6
        with:
          file: docker/makers-dockerfile
          push: true
          # sbom: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}:push
            ${{ env.DOCKER_IMAGE_NAME }}:push
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BRANCH=test_push


      - if: ${{ github.event_name == 'release' }}
        name: Build and push release docker image to GitHub Container Registry and Docker Hub with tags
        id: release
        uses: docker/build-push-action@v6
        with:
          file: docker/makers-dockerfile
          push: true
          # sbom: true
          tags: |
              ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BRANCH=main
