name: Create and publish a docker image to GitHub Container Registry and Docker-hub

on:
  pull_request:
    branches: main/**
    paths:
      - 'docker/makers-dockerfile'

  push:
    tags:
      - 'v*'
    paths:
      - 'docker/makers-dockerfile'


jobs:
  build-and-push-image-to-ghcr:
    runs-on: ubuntu-24.04


    env:
      GHCR_REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}


    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract metadata (tags, labels) for docker
        id: meta_ghcr
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}


      - if: ${{ github.event_name == 'push' }}
        name: Build and push docker image to ghcr.io
        id: push_ghcr
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/makers-dockerfile
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:test_push
          labels: ${{ steps.meta_ghcr.outputs.labels }}


      - if: ${{ github.event_name == 'pull_request' }}
        name: Build and push docker image to ghcr.io with tags
        id: pull_request_ghcr
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/makers-dockerfile
          push: true
          tags: ${{ steps.meta_ghcr.outputs.tags }}
          labels: ${{ steps.meta_ghcr.outputs.labels }}


      # - if: ${{ github.event_name == 'pull_request' }}
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.GHCR_REGISTRY }}/bargfred/cicdtemplate
      #     # subject-name: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.pull_request_ghcr.outputs.digest }}
      #     push-to-registry: true


  build-and-push-image-to-docker:
    runs-on: ubuntu-24.04
    needs: build-and-push-image-to-ghcr


    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/makers-devops


    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Log in to the docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta_docker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
  

      - if: ${{ github.event_name == 'push' }}
        name: Build and push docker image to docker-hub
        id: push_docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/makers-dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:test_push
          labels: ${{ steps.meta_docker.outputs.labels }}


      - if: ${{ github.event_name == 'pull_request' }}
        name: Build and push docker image to docker-hub
        id: pull_request_docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/makers-dockerfile
          push: true
          tags: ${{ steps.meta_docker.outputs.tags }}
          labels: ${{ steps.meta_docker.outputs.labels }}
  
          
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     # subject-name: ${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.pull_request_docker.outputs.digest }}
      #     push-to-registry: true
